/**
 * Seed data for COA Management, Calendar, Recommendations,
 * Hierarchical Issues, and Notifications.
 * Ported from RAIL_PRAVAH_FRONTEND server.ts Mumbai Central Line mock data.
 */
import {
  CoaServiceRequest,
  CoaCalendarBlock,
  CoaRecommendation,
  HierarchicalIssue,
  SlotNotification,
} from '../types/coa-frontend.types.js';

export const SEED_COA_REQUESTS: CoaServiceRequest[] = [
  {
    id: 'req-101',
    department: 'Engineering Department',
    trackArea: 'Ghatkopar - Vikhroli',
    description: 'Deep screening and sleeper replacement on Down Slow track (Beside PF #3)',
    priority: 'High',
    preferredSlot: '2026-08-29 01:30 - 04:30',
    status: 'Pending',
    createdAt: '2026-08-28 09:15',
    workType: 'Track Renewal & Deep Screening',
    submittedBy: 'P-Way Kurla Section',
  },
  {
    id: 'req-102',
    department: 'Traction Distribution Department',
    trackArea: 'Ghatkopar - Vikhroli',
    description: 'OHE Catenary contact wire dropper inspection & neutral section overhaul',
    priority: 'High',
    preferredSlot: '2026-08-29 01:30 - 04:30',
    status: 'Pending',
    createdAt: '2026-08-28 10:20',
    workType: 'OHE Catenary Maintenance',
    submittedBy: 'TRD Vidyavihar Depot',
  },
  {
    id: 'req-103',
    department: 'Signal and Telecommunication Department',
    trackArea: 'Ghatkopar - Vikhroli',
    description: 'Digital Axle Counter (DAC) track resonator calibration & signal head lamp replacement',
    priority: 'High',
    preferredSlot: '2026-08-29 02:00 - 04:00',
    status: 'Pending',
    createdAt: '2026-08-28 11:05',
    workType: 'Signal & Interlocking',
    submittedBy: 'S&T Ghatkopar Sub-Division',
  },
  {
    id: 'req-104',
    department: 'Signal and Telecommunication Department',
    trackArea: 'Kasara - Khardi (Kasara Branch)',
    description: 'Emergency Electronic Interlocking (EI) panel software firmware patching & fail-safe audit',
    priority: 'High',
    preferredSlot: '2026-08-29 02:00 - 04:30',
    status: 'Pending',
    createdAt: '2026-08-28 12:40',
    workType: 'Electronic Interlocking Patch',
    submittedBy: 'S&T North East Branch',
  },
  {
    id: 'req-105',
    department: 'Traction Distribution Department',
    trackArea: 'Dadar - Matunga',
    description: 'OHE Mast bracket tightening and insulator washing on Up Fast line',
    priority: 'Medium',
    preferredSlot: '2026-08-29 11:30 - 13:30',
    status: 'Pending',
    createdAt: '2026-08-28 14:10',
    workType: 'OHE Insulator Washing',
    submittedBy: 'TRD Dadar Depot',
  },
  {
    id: 'req-106',
    department: 'Engineering Department',
    trackArea: 'Dadar - Matunga',
    description: 'Diamond point crossover lubrication and check-rail clearance setting',
    priority: 'Medium',
    preferredSlot: '2026-08-29 11:45 - 13:45',
    status: 'Pending',
    createdAt: '2026-08-28 14:50',
    workType: 'Point Crossover Maintenance',
    submittedBy: 'P-Way Dadar Division',
  },
  {
    id: 'req-107',
    department: 'Engineering Department',
    trackArea: 'Neral - Karjat - Khopoli (Khopoli Branch)',
    description: 'Hill section boulder net fencing & mountain rail ultrasonic flaw detection (USFD)',
    priority: 'Medium',
    preferredSlot: '2026-08-30 01:00 - 04:00',
    status: 'Pending',
    createdAt: '2026-08-28 16:30',
    workType: 'USFD Ultrasonic Testing',
    submittedBy: 'P-Way Karjat Subdivision',
  },
  {
    id: 'req-108',
    department: 'Engineering Department',
    trackArea: 'Thane - Mulund',
    description: 'Creek Bridge #34 girder paint coating touchup and expansion joint clearance',
    priority: 'Low',
    preferredSlot: '2026-08-30 13:00 - 15:00',
    status: 'Pending',
    createdAt: '2026-08-28 17:00',
    workType: 'Bridge Structure Care',
    submittedBy: 'Bridge Inspector Thane',
  },
  {
    id: 'req-109',
    department: 'Signal and Telecommunication Department',
    trackArea: 'Thane - Mulund',
    description: 'Routine optical fiber cable (OFC) route marker verification on Up Slow track',
    priority: 'Low',
    preferredSlot: '2026-08-30 13:15 - 14:45',
    status: 'Pending',
    createdAt: '2026-08-28 17:30',
    workType: 'Telecom OFC Maintenance',
    submittedBy: 'Telecom Thane Unit',
  },
];

export const SEED_CALENDAR_BLOCKS: CoaCalendarBlock[] = [
  {
    id: 'cal-1',
    title: 'Cluster CL-89: Ghatkopar-Vikhroli Mega Shadow',
    station: 'Ghatkopar - Vikhroli',
    department: 'Engineering + TRD + S&T',
    date: '2026-08-29',
    startTime: '01:30',
    endTime: '04:30',
    priority: 'High',
    status: 'approved',
    description: '3-Department synchronized track renewal, catenary overhaul & axle counter calibration',
    clusterId: 'CL-89',
    isClustered: true,
    trainsAffected: 4,
  },
  {
    id: 'cal-2',
    title: 'S&T Electronic Interlocking Firmware Upgrade',
    station: 'Kasara - Khardi (Kasara Branch)',
    department: 'Signal and Telecommunication Department',
    date: '2026-08-29',
    startTime: '02:00',
    endTime: '04:30',
    priority: 'High',
    status: 'approved',
    description: 'Fail-safe dual redundancy testing in single line hill section',
    isClustered: false,
    trainsAffected: 2,
  },
  {
    id: 'cal-3',
    title: 'Cluster CL-92: Dadar Point & OHE Washing',
    station: 'Dadar - Matunga',
    department: 'Traction Distribution + Engineering',
    date: '2026-08-29',
    startTime: '11:30',
    endTime: '13:30',
    priority: 'Medium',
    status: 'pending',
    description: 'Mid-day shadow window utilizing freight lull between peak services',
    clusterId: 'CL-92',
    isClustered: true,
    trainsAffected: 3,
  },
  {
    id: 'cal-4',
    title: 'Emergency Rail Fracture Weld Restoration',
    station: 'Kalyan - Thakurli',
    department: 'Engineering Department',
    date: '2026-08-28',
    startTime: '16:00',
    endTime: '17:30',
    priority: 'Emergency',
    status: 'emergency',
    description: 'Immediate ultrasonic fracture clamp and flash butt thermit weld',
    isClustered: false,
    trainsAffected: 6,
  },
  {
    id: 'cal-5',
    title: 'Bridge Girder Inspection & Telecom OFC',
    station: 'Thane - Mulund',
    department: 'Engineering + S&T',
    date: '2026-08-30',
    startTime: '13:00',
    endTime: '15:00',
    priority: 'Low',
    status: 'pending',
    description: 'Creek Bridge non-intrusive girder scan & fiber optics line markers',
    clusterId: 'CL-94',
    isClustered: true,
    trainsAffected: 1,
  },
];

export const SEED_RECOMMENDATIONS: CoaRecommendation[] = [
  {
    id: 'rec-clust-01',
    cluster_id: 'CL-89',
    isClustered: true,
    stations: ['Ghatkopar', 'Vikhroli'],
    station_text: 'Ghatkopar - Vikhroli (Down Slow Line)',
    proposed_slot: '2026-08-29 01:30 - 04:30 (Tomorrow Night)',
    slot_window: '01:30 - 04:30 (3.0 hrs)',
    priority_tier: 'High',
    trains_affected_clustered: 4,
    trains_affected_individual_sum: 21,
    trains_saved_count: 17,
    status: 'pending_review',
    departments: [
      'Engineering Department',
      'Traction Distribution Department',
      'Signal and Telecommunication Department',
    ],
    request_ids: ['req-101', 'req-102', 'req-103'],
    plain_language_reason:
      'All 3 departments requested high-priority work on the same Ghatkopar-Vikhroli Down Slow segment. By merging P-Way deep screening, TRD catenary overhaul, and S&T axle counter calibration into a unified 3-hour night block (01:30 - 04:30), total train delays drop from 21 trains to only 4 regulated night freight rakes, saving 17 train delays.',
    safety_check_passed: true,
    safety_notes:
      'Safe work types: OHE power isolation permits ground P-Way tamping and non-electrified S&T signal calibration concurrently.',
    createdAt: '2026-08-28 20:00',
  },
  {
    id: 'rec-indiv-02',
    isClustered: false,
    stations: ['Kasara', 'Khardi'],
    station_text: 'Kasara - Khardi (Kasara Branch Single Line)',
    proposed_slot: '2026-08-29 02:00 - 04:30 (Tomorrow Night)',
    slot_window: '02:00 - 04:30 (2.5 hrs)',
    priority_tier: 'High',
    trains_affected_clustered: 2,
    trains_affected_individual_sum: 8,
    trains_saved_count: 6,
    status: 'pending_review',
    departments: ['Signal and Telecommunication Department'],
    request_ids: ['req-104'],
    plain_language_reason:
      'High-priority S&T Electronic Interlocking request on Kasara Branch has no compatible partner in the hill corridor. Scheduled as an individual AI-optimized slot during the lowest traffic frequency window (02:00 - 04:30), granting immediate high-priority clearance while regulating only 2 night freight trains.',
    safety_check_passed: true,
    safety_notes: 'Individual block with full station master interlocking protection.',
    createdAt: '2026-08-28 20:05',
  },
];

export const SEED_HIERARCHICAL_ISSUES: HierarchicalIssue[] = [
  {
    id: 'h-iss-102',
    ticketNo: 'CR-WRK-2026-0892',
    currentStatus: 'Escalated to COA',
    station: 'Vidyavihar',
    zone: 'Central Zone',
    department: 'Traction Distribution Department',
    supervisor: {
      name: 'Sunil G. Sawant',
      empId: 'SUP-CR-3105',
      designation: 'SSE / Traction Distribution TRD (Kurla Substation)',
      phone: '+91 98202 88412',
      depot: 'Kurla TRD Power & Catenary Substation (Km 15/04)',
    },
    zonalHead: {
      name: 'Virendra K. Meena',
      empId: 'ZON-CR-1102',
      designation: 'Chief Track Engineer (CTE / HQ CSMT)',
      zone: 'Central Railway Zone',
    },
    departmentHead: {
      name: 'Dr. Pradeep Verma',
      empId: 'DPT-CR-5520',
      designation: 'Sr. Divisional Electrical Engineer (Sr. DEE / TRD Central)',
      department: 'Traction Distribution Department',
    },
    originalRequest: {
      title: '25kV OHE Phase-Break Insulator Fire Arc Damage',
      department: 'Traction Distribution Department',
      station: 'Vidyavihar',
      trackSection: 'GK – VV (Ghatkopar - Vidyavihar)',
      nearestKmPost: 'Km 16/08',
      lineType: 'Up Slow',
      coordinates: { lat: 19.0798, lng: 72.8987 },
      description: 'Phase-break insulator sustained flashover arc damage during power restoration. Visible charring on bottom shed surface. Adjacent catenary tensioner shows heat-induced spring fatigue. Immediate OHE power block required before next morning peak.',
      priority: 'Emergency',
      estimatedFixTimeMinutes: 120,
      media: [],
      technicalNotes: 'Leakage current reading: 38 mA (critical threshold at 20 mA). Auto-reclosure tripped 3x in 15 mins.',
      reportedBy: {
        name: 'Dinesh B. Kamble',
        empId: 'WRK-CR-2087',
        phone: '+91 98210 45521',
        gangNo: 'TRD Gang #5 (Catenary Crew)',
      },
      reportedAt: '2026-08-27 23:45',
    },
    activeRequest: {
      title: '25kV OHE Phase-Break Insulator Fire Arc Damage',
      department: 'Traction Distribution Department',
      station: 'Vidyavihar',
      trackSection: 'GK – VV (Ghatkopar - Vidyavihar)',
      nearestKmPost: 'Km 16/08',
      lineType: 'Up Slow',
      coordinates: { lat: 19.0798, lng: 72.8987 },
      description: 'Phase-break insulator sustained flashover arc damage during power restoration. Visible charring on bottom shed surface. Adjacent catenary tensioner shows heat-induced spring fatigue. Immediate OHE power block required before next morning peak.',
      priority: 'Emergency',
      estimatedFixTimeMinutes: 120,
      media: [],
      technicalNotes: 'Leakage current reading: 38 mA (critical threshold at 20 mA). Auto-reclosure tripped 3x in 15 mins.',
    },
    escalatedToZonalAt: '2026-08-28 01:00',
    zonalEscalationReason: 'Emergency catenary fault requiring cross-section coordination',
    escalatedToDeptAt: '2026-08-28 03:30',
    deptEscalationReason: 'OHE isolation and emergency block sanction required from Sr. DEE',
    escalatedToCoaAt: '2026-08-28 06:00',
    coaEscalationReason: 'Emergency block request during peak hour window requires COA Master Controller approval for traffic regulation',
    modificationHistory: [
      {
        id: 'mod-init-102',
        level: 'Worker',
        modifiedBy: { name: 'Dinesh B. Kamble', empId: 'WRK-CR-2087', role: 'TRD Catenary Lineman', department: 'Traction Distribution Department' },
        dateTime: '2026-08-27 23:45',
        changes: 'Original field defect report logged',
        remarks: 'Phase-break insulator flashover observed during late-night power restoration.',
        actionTaken: 'Reported to TRD Supervisor on emergency protocol',
      },
      {
        id: 'mod-esc-102-1',
        level: 'Supervisor',
        modifiedBy: { name: 'Sunil G. Sawant', empId: 'SUP-CR-3105', role: 'SSE / TRD', department: 'Traction Distribution Department' },
        dateTime: '2026-08-28 01:00',
        changes: 'Verified insulator damage and recommended emergency OHE power block',
        remarks: 'Leakage 38 mA confirmed. Recommended immediate power block.',
        actionTaken: 'Escalated to Zonal Head',
      },
    ],
    createdAt: '2026-08-27 23:45',
    updatedAt: '2026-08-28 06:00',
  },
  {
    id: 'h-iss-101',
    ticketNo: 'CR-WRK-2026-0891',
    currentStatus: 'Under Supervisor Review',
    station: 'Dadar',
    zone: 'Central Zone',
    department: 'Engineering',
    supervisor: {
      name: 'Rajesh K. Shinde',
      empId: 'SUP-CR-3104',
      designation: 'SSE / P-Way (Dadar Section)',
      phone: '+91 98201 44521',
      depot: 'Dadar P-Way Maintenance Depot (Km 9/12)',
    },
    zonalHead: {
      name: 'Virendra K. Meena',
      empId: 'ZON-CR-1102',
      designation: 'Chief Track Engineer (CTE / HQ CSMT)',
      zone: 'Central Railway Zone',
    },
    departmentHead: {
      name: 'Dr. Pradeep Verma',
      empId: 'DPT-CR-5520',
      designation: 'Sr. Divisional Engineer (Sr. DEN / Central Line)',
      department: 'Engineering Department',
    },
    originalRequest: {
      title: 'Rail Joint Fracture at Km 11/14 (Down Slow)',
      department: 'Engineering',
      station: 'Dadar',
      trackSection: 'DR – MT (Dadar - Matunga)',
      nearestKmPost: 'Km 11/14',
      lineType: 'Down Slow',
      coordinates: { lat: 19.0269, lng: 72.8488 },
      description: 'Transverse rail head fracture at glued insulated joint (GIJ), detected during night patrolling. Joint gap exceeds 6mm limit. Speed restriction imposed at 15 km/h.',
      priority: 'High',
      estimatedFixTimeMinutes: 90,
      media: [],
      technicalNotes: 'GIJ failure type: transverse head crack. UTS reading: 880 MPa vs spec 1080 MPa.',
      reportedBy: {
        name: 'Suresh R. Patil',
        empId: 'WRK-CR-2041',
        phone: '+91 97692 31204',
        gangNo: 'P-Way Gang #12',
      },
      reportedAt: '2026-08-28 03:30',
    },
    activeRequest: {
      title: 'Rail Joint Fracture at Km 11/14 (Down Slow)',
      department: 'Engineering',
      station: 'Dadar',
      trackSection: 'DR – MT (Dadar - Matunga)',
      nearestKmPost: 'Km 11/14',
      lineType: 'Down Slow',
      coordinates: { lat: 19.0269, lng: 72.8488 },
      description: 'Transverse rail head fracture at glued insulated joint (GIJ), detected during night patrolling. Joint gap exceeds 6mm limit. Speed restriction imposed at 15 km/h.',
      priority: 'High',
      estimatedFixTimeMinutes: 90,
      media: [],
      technicalNotes: 'GIJ failure type: transverse head crack. UTS reading: 880 MPa vs spec 1080 MPa.',
    },
    modificationHistory: [
      {
        id: 'mod-init-101',
        level: 'Worker',
        modifiedBy: { name: 'Suresh R. Patil', empId: 'WRK-CR-2041', role: 'Field Track Maintainer Gr-IV', department: 'Engineering' },
        dateTime: '2026-08-28 03:30',
        changes: 'Original field defect report logged',
        remarks: 'Rail head fracture detected during night patrolling.',
        actionTaken: 'Reported to Section Supervisor for review',
      },
    ],
    createdAt: '2026-08-28 03:30',
    updatedAt: '2026-08-28 03:30',
  },
];

export const SEED_NOTIFICATIONS: SlotNotification[] = [
  {
    id: 'notif-init-01',
    slotId: 'slot-prv-gkv-01',
    slotCode: 'PRV-2026-0829-GKV',
    title: 'COA Approved प्रवाहPlan Slot: PRV-2026-0829-GKV',
    message: 'COA Master Traffic Controller approved and sanctioned unified corridor maintenance block at Ghatkopar – Vikhroli / Kurla Corridor on 2026-08-29 (01:30 – 04:30 IST). Zero regular train delays guaranteed. Dispatched to Department Head, Zonal Head, Supervisor, and Worker inboxes.',
    timing: '01:30 – 04:30 IST',
    startTime: '01:30',
    endTime: '04:30',
    date: '2026-08-29',
    location: 'Ghatkopar – Vikhroli / Kurla Corridor (Km 19/20 to 23/15)',
    workName: 'Joint Multi-Dept Possession: Deep Track Screening, 25kV Insulator Overhaul & Axle Counter Tuning',
    departments: ['Engineering (P-Way)', 'TRD (Electrical)', 'S&T (Signaling)'],
    recipientRoles: ['department_user', 'zonal_head', 'supervisor', 'worker'],
    recipientDepts: ['Engineering (P-Way)', 'TRD (Electrical)', 'S&T (Signaling)'],
    createdAt: new Date().toISOString(),
    sanctionedBy: 'COA Master Traffic Controller',
    status: 'active',
  },
];
