import { TrainSchedule } from '../types/database.types.js';

export const INITIAL_TRAIN_SCHEDULES: TrainSchedule[] = [
  // ─── CSMT – Byculla – Dadar (Down Slow / Down Fast) ────────────────────────
  {
    id: "trn-97001",
    train_no: "97001",
    train_name: "CSMT – Thane Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "CSMT – Byculla",
    station: "CSMT",
    line_type: "Down Slow Line",
    scheduled_slot: "05:12",
    origin: "CSMT",
    destination: "Thane",
    frequency_minutes: 6,
    priority_tier: 3,
  },
  {
    id: "trn-97003",
    train_no: "97003",
    train_name: "CSMT – Kalyan Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "CSMT – Byculla",
    station: "Byculla",
    line_type: "Down Slow Line",
    scheduled_slot: "06:20",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 6,
    priority_tier: 3,
  },
  {
    id: "trn-95301",
    train_no: "95301",
    train_name: "CSMT – Kalyan Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Byculla – Dadar",
    station: "Dadar",
    line_type: "Down Fast Line",
    scheduled_slot: "07:15",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-12111",
    train_no: "12111",
    train_name: "CSMT – Amravati Express",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Byculla – Dadar",
    station: "Dadar",
    line_type: "Down Fast Line",
    scheduled_slot: "08:10",
    origin: "CSMT",
    destination: "Amravati",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97015",
    train_no: "97015",
    train_name: "CSMT – Dombivli Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Dadar – Matunga",
    station: "Dadar",
    line_type: "Down Slow Line",
    scheduled_slot: "09:30",
    origin: "CSMT",
    destination: "Dombivli",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95403",
    train_no: "95403",
    train_name: "CSMT – Kasara Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Dadar – Matunga",
    station: "Matunga",
    line_type: "Down Fast Line",
    scheduled_slot: "10:45",
    origin: "CSMT",
    destination: "Kasara",
    frequency_minutes: 12,
    priority_tier: 2,
  },
  {
    id: "trn-12859",
    train_no: "12859",
    train_name: "Gitanjali Express (CSMT – HWH)",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Dadar – Matunga",
    station: "Dadar",
    line_type: "Down Fast Line",
    scheduled_slot: "11:20",
    origin: "CSMT",
    destination: "Howrah Jn",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97045",
    train_no: "97045",
    train_name: "CSMT – Thane Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Matunga – Kurla",
    station: "Kurla",
    line_type: "Down Slow Line",
    scheduled_slot: "12:15",
    origin: "CSMT",
    destination: "Thane",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95503",
    train_no: "95503",
    train_name: "CSMT – Karjat Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Matunga – Kurla",
    station: "Kurla",
    line_type: "Down Fast Line",
    scheduled_slot: "13:00",
    origin: "CSMT",
    destination: "Karjat",
    frequency_minutes: 10,
    priority_tier: 2,
  },
  {
    id: "trn-97061",
    train_no: "97061",
    train_name: "CSMT – Kalyan Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Kurla – Ghatkopar",
    station: "Ghatkopar",
    line_type: "Down Slow Line",
    scheduled_slot: "14:10",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95315",
    train_no: "95315",
    train_name: "CSMT – Kalyan Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Kurla – Ghatkopar",
    station: "Ghatkopar",
    line_type: "Down Fast Line",
    scheduled_slot: "14:25",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-12051",
    train_no: "12051",
    train_name: "Jan Shatabdi Express (CSMT – MAO)",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Kurla – Ghatkopar",
    station: "Kurla",
    line_type: "Down Fast Line",
    scheduled_slot: "14:40",
    origin: "CSMT",
    destination: "Madgaon",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97089",
    train_no: "97089",
    train_name: "CSMT – Thane Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Ghatkopar – Vikhroli",
    station: "Vikhroli",
    line_type: "Down Slow Line",
    scheduled_slot: "15:15",
    origin: "CSMT",
    destination: "Thane",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-97091",
    train_no: "97091",
    train_name: "CSMT – Kalyan Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Ghatkopar – Vikhroli",
    station: "Ghatkopar",
    line_type: "Down Slow Line",
    scheduled_slot: "15:35",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95325",
    train_no: "95325",
    train_name: "CSMT – Dombivli Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Ghatkopar – Vikhroli",
    station: "Vikhroli",
    line_type: "Down Fast Line",
    scheduled_slot: "15:45",
    origin: "CSMT",
    destination: "Dombivli",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-11009",
    train_no: "11009",
    train_name: "Sinhagad Express (CSMT – PUNE)",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Ghatkopar – Vikhroli",
    station: "Vikhroli",
    line_type: "Down Fast Line",
    scheduled_slot: "15:55",
    origin: "CSMT",
    destination: "Pune Jn",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97093",
    train_no: "97093",
    train_name: "CSMT – Diva Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Bhandup – Mulund",
    station: "Bhandup",
    line_type: "Down Slow Line",
    scheduled_slot: "16:05",
    origin: "CSMT",
    destination: "Diva",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95333",
    train_no: "95333",
    train_name: "CSMT – Kalyan Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Bhandup – Mulund",
    station: "Mulund",
    line_type: "Down Fast Line",
    scheduled_slot: "16:20",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-11057",
    train_no: "11057",
    train_name: "Amritsar Express (CSMT – ASR)",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Thane – Mulund",
    station: "Thane",
    line_type: "Down Fast Line",
    scheduled_slot: "16:35",
    origin: "CSMT",
    destination: "Amritsar",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97095",
    train_no: "97095",
    train_name: "CSMT – Thane Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Thane – Mulund",
    station: "Thane",
    line_type: "Down Slow Line",
    scheduled_slot: "16:50",
    origin: "CSMT",
    destination: "Thane",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-97097",
    train_no: "97097",
    train_name: "CSMT – Karjat Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Thane – Diva",
    station: "Diva",
    line_type: "Down Slow Line",
    scheduled_slot: "17:10",
    origin: "CSMT",
    destination: "Karjat",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95341",
    train_no: "95341",
    train_name: "CSMT – Kalyan Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Thane – Diva",
    station: "Kalva",
    line_type: "Down Fast Line",
    scheduled_slot: "17:25",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-22221",
    train_no: "22221",
    train_name: "CSMT – NZM Rajdhani Express",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Thane – Diva",
    station: "Thane",
    line_type: "Down Fast Line",
    scheduled_slot: "17:40",
    origin: "CSMT",
    destination: "Hazrat Nizamuddin",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97099",
    train_no: "97099",
    train_name: "CSMT – Asangaon Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Diva – Kalyan",
    station: "Dombivli",
    line_type: "Down Slow Line",
    scheduled_slot: "18:05",
    origin: "CSMT",
    destination: "Asangaon",
    frequency_minutes: 6,
    priority_tier: 3,
  },
  {
    id: "trn-95345",
    train_no: "95345",
    train_name: "CSMT – Kalyan Fast Local",
    service_type: "fast_local",
    direction: "DOWN",
    corridor_section: "Diva – Kalyan",
    station: "Kalyan",
    line_type: "Down Fast Line",
    scheduled_slot: "18:25",
    origin: "CSMT",
    destination: "Kalyan",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-97103",
    train_no: "97103",
    train_name: "CSMT – Titwala Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Kalyan – Thakurli",
    station: "Kalyan",
    line_type: "Down Slow Line",
    scheduled_slot: "18:45",
    origin: "CSMT",
    destination: "Titwala",
    frequency_minutes: 6,
    priority_tier: 3,
  },
  {
    id: "trn-12123",
    train_no: "12123",
    train_name: "Deccan Queen Express (CSMT – PUNE)",
    service_type: "mail_express",
    direction: "DOWN",
    corridor_section: "Kalyan – Thakurli",
    station: "Kalyan",
    line_type: "Down Fast Line",
    scheduled_slot: "19:05",
    origin: "CSMT",
    destination: "Pune Jn",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97115",
    train_no: "97115",
    train_name: "CSMT – Kasara Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Asangaon – Kasara",
    station: "Kasara",
    line_type: "North Hill Track",
    scheduled_slot: "20:30",
    origin: "CSMT",
    destination: "Kasara",
    frequency_minutes: 15,
    priority_tier: 3,
  },
  {
    id: "trn-97121",
    train_no: "97121",
    train_name: "CSMT – Khopoli Slow Local",
    service_type: "slow_local",
    direction: "DOWN",
    corridor_section: "Karjat – Palasdari",
    station: "Karjat",
    line_type: "Mountain Ghat Track",
    scheduled_slot: "21:15",
    origin: "CSMT",
    destination: "Khopoli",
    frequency_minutes: 20,
    priority_tier: 3,
  },
  // ─── UP Direction Suburban Locals & Express ────────────────────────────────
  {
    id: "trn-97202",
    train_no: "97202",
    train_name: "Kalyan – CSMT Slow Local",
    service_type: "slow_local",
    direction: "UP",
    corridor_section: "Kalyan – Thakurli",
    station: "Kalyan",
    line_type: "Up Slow Line",
    scheduled_slot: "07:05",
    origin: "Kalyan",
    destination: "CSMT",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95304",
    train_no: "95304",
    train_name: "Kalyan – CSMT Fast Local",
    service_type: "fast_local",
    direction: "UP",
    corridor_section: "Thane – Diva",
    station: "Thane",
    line_type: "Up Fast Line",
    scheduled_slot: "08:15",
    origin: "Kalyan",
    destination: "CSMT",
    frequency_minutes: 6,
    priority_tier: 2,
  },
  {
    id: "trn-97224",
    train_no: "97224",
    train_name: "Thane – CSMT Slow Local",
    service_type: "slow_local",
    direction: "UP",
    corridor_section: "Ghatkopar – Vikhroli",
    station: "Ghatkopar",
    line_type: "Up Slow Line",
    scheduled_slot: "09:20",
    origin: "Thane",
    destination: "CSMT",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95310",
    train_no: "95310",
    train_name: "Dombivli – CSMT Fast Local",
    service_type: "fast_local",
    direction: "UP",
    corridor_section: "Kurla – Ghatkopar",
    station: "Kurla",
    line_type: "Up Fast Line",
    scheduled_slot: "10:10",
    origin: "Dombivli",
    destination: "CSMT",
    frequency_minutes: 6,
    priority_tier: 2,
  },
  {
    id: "trn-97248",
    train_no: "97248",
    train_name: "Kalyan – CSMT Slow Local",
    service_type: "slow_local",
    direction: "UP",
    corridor_section: "Dadar – Matunga",
    station: "Dadar",
    line_type: "Up Slow Line",
    scheduled_slot: "14:15",
    origin: "Kalyan",
    destination: "CSMT",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  {
    id: "trn-95322",
    train_no: "95322",
    train_name: "Kasara – CSMT Fast Local",
    service_type: "fast_local",
    direction: "UP",
    corridor_section: "Dadar – Matunga",
    station: "Dadar",
    line_type: "Up Fast Line",
    scheduled_slot: "15:30",
    origin: "Kasara",
    destination: "CSMT",
    frequency_minutes: 8,
    priority_tier: 2,
  },
  {
    id: "trn-12124",
    train_no: "12124",
    train_name: "Deccan Queen Express (PUNE – CSMT)",
    service_type: "mail_express",
    direction: "UP",
    corridor_section: "Dadar – Matunga",
    station: "Dadar",
    line_type: "Up Fast Line",
    scheduled_slot: "16:00",
    origin: "Pune Jn",
    destination: "CSMT",
    frequency_minutes: 0,
    priority_tier: 1,
  },
  {
    id: "trn-97262",
    train_no: "97262",
    train_name: "Thane – CSMT Slow Local",
    service_type: "slow_local",
    direction: "UP",
    corridor_section: "Byculla – Dadar",
    station: "Byculla",
    line_type: "Up Slow Line",
    scheduled_slot: "17:15",
    origin: "Thane",
    destination: "CSMT",
    frequency_minutes: 5,
    priority_tier: 3,
  },
  // ─── Heavy Freight & Parcel Rakes (5th & 6th Line / Goods Corridors) ──────
  {
    id: "trn-frt-01",
    train_no: "BTPN/JNPT-99",
    train_name: "JNPT Container / Petroleum Freight",
    service_type: "freight",
    direction: "DOWN",
    corridor_section: "Kurla – Vidyavihar",
    station: "Kurla",
    line_type: "5th Line (Bypass Corridor)",
    scheduled_slot: "14:30",
    origin: "JNPT Port",
    destination: "Tuglakabad Goods",
    frequency_minutes: 0,
    priority_tier: 4,
  },
  {
    id: "trn-frt-02",
    train_no: "BOXN/CR-44",
    train_name: "Coal Rake (Trombay Thermal Siding)",
    service_type: "freight",
    direction: "UP",
    corridor_section: "Thane – Diva",
    station: "Diva",
    line_type: "5th & 6th Line (Fast Freight & Express)",
    scheduled_slot: "15:40",
    origin: "Nagpur Goods",
    destination: "Trombay Siding",
    frequency_minutes: 0,
    priority_tier: 4,
  },
];
